version: "3"

services:
  posgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: paypay_challenge
    ports:
      - "5432:5432"